export const employeeParams = {
    sesionId: '',
    fullName: '',
    employeeNumber: '',
    status: '',
    gender: '',
    marital: '',
    businessName: '',
    birthday: '',
    certificate: '',
    emergencyContact: '',
    emergencyPhone: '',
    barcode: '',
    jobTitle: '',
    workPhone: '',
    mobilePhone: '',
    workEmail: '',
    workLocation: '',
    lastCheckIn: '',
    lastCheckOut: '',
    description: '',
    address: {
        id: '',
        name: '',
        postalCode: '',
        latitude: '',
        longitude: '',
        phoneNumber: '',
        region: '',
        city: '',
        description: '',
    },
    store: {
        id: '',
        name: '',
        storeNumber: '',
        status: '',
        phoneNumber: '',
        mail: '',
        openingTime: '',
        closingTime: '',
        coordinates: '',
        description: '',
        address: '',
    },
    rfc: '',
    nss: '',
}

export const employeeHeaders = {
    employeeId: 0,
    name: "",
    employeeNumber: "",
    status: "AC",
    city: "",
    dateType: "",
    startDate: "",
    finalDate: "",
    storeId: 0,
    pagination: 0
}

export const employeeForm = {
    sesionId: "SES25270322201717",
    fullName: '',
    gender: '',
    marital: '',
    rfc: '',
    nss: '',
    businessName: '',
    birthday: '',
    certificate: "101010",
    emergencyContact: '',
    emergencyPhone: "9983226937",
    barcode: null,
    jobTitle: '',
    workPhone: null,
    mobilePhone: '',
    workEmail: '',
    workLocation: "000122112,-0221212",
    lastCheckIn: '',
    lastCheckOut: '',
    description: '',
    bankAccountId: 0,
    jobId: 0,
    parentId: 0,
    employeeRelativesId: 0,
    resourceCalendarId: 0,
    resourceId: 0,
    lastAttendanceId: 0,
    leaveManagerId: 0,
    departmentId: 0,
    storeId: '',
};

export const employeeFormValid = {
    sesionId: false,
    fullName: false,
    gender: false,
    marital: false,
    rfc: false,
    nss: false,
    businessName: false,
    birthday: false,
    certificate: false,
    emergencyContact: false,
    emergencyPhone: false,
    barcode: false,
    jobTitle: false,
    workPhone: false,
    mobilePhone: false,
    workEmail: false,
    workLocation: false,
    lastCheckIn: false,
    lastCheckOut: false,
    description: false,
    bankAccountId: false,
    jobId: false,
    parentId: false,
    employeeRelativesId: false,
    resourceCalendarId: false,
    resourceId: false,
    lastAttendanceId: false,
    leaveManagerId: false,
    departmentId: false,
    storeId: false,
}